### ISSUE TITLE
Travis build is broken

### ISSUE THREAD

**Issue by ePaul** [zalando/restful-api-guidelines#597]
The last master build one month ago did still work, now the [same build is broken](https://travis-ci.org/github/zalando/restful-api-guidelines/builds/703500390).

```
docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output index.adoc
no implicit conversion of nil into String
  Use --trace for backtrace
```

Running with `--trace` we can find the root cause to be:

```
docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf --trace -D /documents/output index.adoc
/usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:108:in `basename': no implicit conversion of nil into String (TypeError)
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:108:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:454:in `convert_section'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:106:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:1020:in `content'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:359:in `add_chapter'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:250:in `convert_document'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/lib/asciidoctor-epub3/converter.rb:106:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:951:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:118:in `convert'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	from /usr/lib/ruby/gems/2.7.0/gems/asciidoctor-epub3-1.5.0.alpha.18/bin/asciidoctor-epub3:28:in `<top (required)>'
	from /usr/bin/asciidoctor-epub3:23:in `load'
	from /usr/bin/asciidoctor-epub3:23:in `<main>'
```

This also is blocking the merge of #596.

**Comment by tkrop** [comment]
I have filled https://github.com/asciidoctor/asciidoctor-epub3/issues/360. To make it quickly work again, I suggest to fallback to an older fixed Docker image version `asciidoctor/docker-asciidoctor:1.1.0`.
